version: '3.8'

services:
  web:
    build: .
    command: ["./wait-for-db.sh", "roamio.c1kos6auqw13.us-east-2.rds.amazonaws.com", "5432", "postgres", "roamio", "python", "run.py"]
    volumes:
      - .:/app
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DB_USER=postgres
      - DB_PASSWORD=roamiopass
      - DB_HOST=roamio.c1kos6auqw13.us-east-2.rds.amazonaws.com  # AWS RDS Endpoint
      - DB_PORT=5432  # PostgreSQL default port
      - DB_NAME=roamio
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
