version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: roamio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: roamiopass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:roamiopass@db:5432/roamio
    depends_on:
      - db

volumes:
  postgres_data: