branch-defaults:
  main:
    environment: roamio-env-prod
    group_suffix: null
environment-defaults:
  roamio-env-prod:
    branch: null
    repository: null
global:
  application_name: roamio-app
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.9
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
