"""Add profile_visibility to User model

Revision ID: 29678428c097
Revises: 
Create Date: 2024-11-07 04:19:02.230752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29678428c097'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_visibility', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_visibility')

    # ### end Alembic commands ###
