"""Add rating column to activities

Revision ID: 8c195390832f
Revises: 
Create Date: 2024-10-21 18:22:14.836610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c195390832f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.drop_column('average_rating')

    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.drop_constraint('itineraries_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('activity_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               nullable=True)

    # ### end Alembic commands ###
    op.execute("UPDATE activities SET rating = 1 WHERE rating IS NULL;")

    # Alter the column to be NOT NULL now that we've filled it
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('rating', nullable=False)  # Now enforce NOT NULL constraint

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('activity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('itineraries_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rating', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True))
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
